{{- if and (.Capabilities.APIVersions.Has "cert-manager.io/v1") .Values.tls.create -}}
kind: Certificate
apiVersion: cert-manager.io/v1
metadata:
  name: {{ include "nextcloud.fullname" . }}
  namespace: {{ include "common.names.namespace" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  dnsNames:
    - {{ .Values.nextcloud.host }}
  {{- with .Values.tls.issuer }}
  issuerRef:
    kind: {{ default "Issuer" .kind }}
    {{- with .group }}
    group: {{ . }}
    {{- end }}
    name: {{ required "Issuer is missing required name" .name }}
  {{- end }}
  secretName: {{ include "nextcloud.tls.secretName" . }}
{{- end -}}
