kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "nextcloud.fullname" . }}
  namespace: {{ include "common.names.namespace" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
{{- range $path, $_ := .Files.Glob "files/phpConfig/*.ini" }}
  {{- base $path | nindent 2 }}: |-
    {{- tpl ($.Files.Get $path) $ | nindent 4 }}
{{- end }}