{{- if .Values.nextcloud.autoscaling.enabled -}}
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: {{ include "common.names.fullname" . }}
  {{- with .Values.nextcloud.autoscaling }}
  minReplicas: {{ .minReplicas }}
  maxReplicas: {{ .maxReplicas }}
  targetCPUUtilizationPercentage: {{ .targetCPUUtilizationPercentage }}
  {{- end }}
{{- end -}}