{{- $username := default "admin" .Values.auth.adminUsername }}
{{- $password := include "common.secrets.passwords.manage" (dict "secret" (include "nextcloud.auth.secretName" .) "key" (include "nextcloud.auth.adminPasswordKey" .) "providedValues" (list "auth.password") "honorProvidedValues" true "context" $) | trimAll "\"" | b64dec }}
{{- if not .Values.nextcloud.existingSecret -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "nextcloud.auth.secretName" . }}
  namespace: {{ include "common.names.namespace" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  username: {{ $username | b64enc | quote }}
  password: {{ $password | b64enc | quote }}
{{- end -}}