{{- if .Values.serviceAccount.create -}}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "nextcloud.serviceAccountName" . }}
  namespace: {{ include "common.names.namespace" . }}
{{- end -}}