kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "nextcloud.proxy.fullname" . }}
  namespace: {{ include "common.names.namespace" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: proxy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: proxy
  template:
    metadata:
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: proxy
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/proxy/configmap.yaml") . | sha256sum }}
    spec:
      restartPolicy: Always
      serviceAccountName: nextcloud
      containers:
        - name: nginx
          image: {{ include "nextcloud.proxy.image" . }}
          ports:
            - name: http
              containerPort: {{ .Values.proxy.containerPort }}
              protocol: TCP
            - name: https
              containerPort: {{ .Values.proxy.sslContainerPort }}
              protocol: TCP
          resources: {}
          volumeMounts:
            {{- include "nextcloud.volumeMounts" . | nindent 12 }}
            - name: config
              mountPath: /etc/nginx/conf.d/
            {{- if .Values.proxy.ssl.enabled }}
            - name: tls
              mountPath: {{ include "nextcloud.tls.mountPath" . }}
            {{- end }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      serviceAccount: nextcloud
      volumes:
        {{- include "nextcloud.volumes" . | nindent 8 }}
        - name: config
          configMap:
            name: nextcloud-proxy
        {{- if .Values.proxy.ssl.enabled }}
        - name: tls
          secret:
            secretName: {{ include "nextcloud.tls.secretName" . }}
        {{- end }}
      dnsPolicy: ClusterFirst
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600