kind: Service
apiVersion: v1
metadata:
  name: {{ include "nextcloud.proxy.fullname" . }}
  namespace: {{ include "common.names.namespace" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  type: {{ .Values.proxy.service.type }}
  {{- if (eq .Values.proxy.service.type "LoadBalancer") }}
  {{- with .Values.proxy.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- end }}
  {{- with .Values.proxy.service.ipFamilies }}
  ipFamilies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.proxy.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
  {{- end }}
  {{- with .Values.proxy.service.sessionAffinity }}
  sessionAffinity: {{ . }}
  {{- end }}
  {{- with .Values.proxy.service.sessionAffinityConfig }}
  sessionAffinityConfig:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.proxy.service.port }}
      targetPort: http
    {{- if .Values.proxy.tls.enabled }}
    - name: https
      protocol: TCP
      port: {{ .Values.proxy.service.sslPort }}
      targetPort: https
    {{- end }}
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: proxy