kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "nextcloud.fpm.fullname" . }}
  namespace: {{ include "common.names.namespace" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: fpm
spec:
  {{- if not .Values.nextcloud.autoscaling.enabled }}
  replicas: {{ .Values.nextcloud.replicaCount }}
  {{- end }}
  strategy:
    {{- toYaml .Values.nextcloud.strategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: fpm
  template:
    metadata:
      creationTimestamp: null
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: fpm
    spec:
      restartPolicy: Always
      serviceAccountName: {{ include "nextcloud.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      initContainers:
        - name: init
          image: {{ include "nextcloud.image" . }}
          imagePullPolicy: {{ include "nextcloud.imagePullPolicy" . }}
          volumeMounts:
            {{- include "nextcloud.volumeMounts" . | nindent 12 }}
          command:
            - php
            - /var/www/html/occ
            - status
      containers:
        - name: php-fpm
          image: {{ include "nextcloud.image" . }}
          imagePullPolicy: {{ include "nextcloud.imagePullPolicy" . }}
          env:
            {{- include "nextcloud.env" . | nindent 12 }}
          ports:
            - name: fcgi
              containerPort: {{ .Values.nextcloud.containerPort }}
              protocol: TCP
          volumeMounts:
            {{- include "nextcloud.volumeMounts" . | nindent 12 }}
          {{- with .Values.nextcloud.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
            tcpSocket:
              port: fcgi
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - php-fpm-healthcheck
            initialDelaySeconds: 10
            periodSeconds: 5
{{/*
        - name: metrics
          image: 'hipages/php-fpm_exporter:latest'
          imagePullPolicy: IfNotPresent
          env:
            - name: PHP_FPM_FIX_PROCESS_COUNT
              value: 'true'
          ports:
            - name: metrics
              containerPort: 9253
              protocol: TCP
          resources:
            limits:
              cpu: 40m
              memory: 32Mi
            requests:
              cpu: 40m
              memory: 32Mi
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /metrics
              port: metrics
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 1
            successThreshold: 1
            failureThreshold: 120
*/}}
      serviceAccount: {{ include "nextcloud.serviceAccountName" . }}
      volumes:
        {{- include "nextcloud.volumes" . | nindent 8 }}



